version: '3.8'

services:
  # location_weather microservice
  location_weather:
    build: ./location_weather
    ports:
      - '5003:5003'
    env_file:
      - ./location_weather/.env
    depends_on:
      - rabbitmq
    restart: on-failure

  geocding:
    build: 
      context: ./geocoding
      dockerfile: Dockerfile.encoder
    ports:
      - '5004:5004'
    env_file:
      - ./geocding/.env
    restart: on-failure