networks:
  weatherwonder_network:
    driver: bridge
    name: weatherwonder_network

services:
  # location_weather microservice
  location_weather:
    build: ./location_weather
    ports:
      - '5003:5003'
    env_file:
      - ./location_weather/.env
    restart: on-failure

  geocoding:
    build: 
      context: ./geocoding
      dockerfile: Dockerfile.encoder
    ports:
      - '5004:5004'
    env_file:
      - ./geocoding/.env
    restart: on-failure

  user:
    build: 
      context: ./user
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ./user/.env
    restart: on-failure

  location:
    build: 
      context: ./location
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
    env_file:
      - ./location/.env
    restart: on-failure

  add_a_location:
    build: 
      context: ./add_a_location
      dockerfile: Dockerfile
    ports:
      - '5010:5010'
    restart: on-failure
    depends_on:
      - location
      - geocoding