volumes:
  pgdata:
    name: esd-pgdata

networks:
  esd-weatherwonder:
    external: true


services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:17.4
    # platform: linux/amd64  # <- required for Mac M1 chip. Otherwise, can remove
    restart: always
    networks:
      - esd-weatherwonder
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong/kong-gateway:3.8
    # platform: linux/amd64  # <- required for Mac M1 chip. Otherwise, can remove
    command: >
      sh -c "kong migrations bootstrap && kong config db_import /usr/local/kong/declarative/gateway.yaml"
    restart: on-failure
    networks:
      - esd-weatherwonder
    env_file:
      - ./.env
    depends_on:
      kong-database:
        condition: service_healthy
    volumes:
      - ./gateway.yaml:/usr/local/kong/declarative/gateway.yaml

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong/kong-gateway:3.8
    # platform: linux/amd64  # <- required for Mac M1 chip. Otherwise, can remove
    restart: always
    networks:
      - esd-weatherwonder
    env_file:
      - ./.env
    depends_on:
      - kong-migration
    ports: # https://docs.konghq.com/gateway/latest/production/networking/default-ports/
      - "8000:8000" # Takes incoming HTTP traffic from Consumers, and forwards it to upstream Services.
      - "8001:8001" # Admin API. Listens for calls from the command line over HTTP.
      - "8002:8002" # Kong Manager (GUI). Listens for HTTP traffic.