networks:
  esd-weatherwonder:
    driver: bridge
    name: esd-weatherwonder

volumes:
  prometheusdata:
    name: esd_prometheusdata 
  grafanadata:
    name: esd_grafanadata 


services:
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong/kong-gateway:3.9
    restart: always
    networks:
      - esd-weatherwonder
    env_file:
      - ./.env
    environment:
      KONG_DATABASE: "off" 
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/gateway.yaml" 
    ports:
      - "8003:8000" # Proxy traffic
      - "8001:8001" # Admin API
      - "8002:8002" # Kong Manager
    volumes:
      - ./gateway.yaml:/usr/local/kong/declarative/gateway.yaml 

  #######################################
  # Prometheus
  #######################################
  prometheus:
    image: prom/prometheus:v3.2.1
    restart: always
    networks:
      - esd-weatherwonder
    ports:
      - "9090:9090"
    volumes:
      - prometheusdata:/prometheus 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


  #######################################
  # Grafana Open Source
  #######################################
  grafana:
    image: grafana/grafana-oss:11.3.4
    restart: always
    networks:
      - esd-weatherwonder
    ports:
      - "13000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
   
  