networks:
  esd-weatherwonder:
    driver: bridge
    name: esd-weatherwonder


services:
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong/kong-gateway:3.9
    restart: always
    networks:
      - esd-weatherwonder
    env_file:
      - ./.env
    environment:
      KONG_DATABASE: "off" 
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/gateway.yaml" 
    # depends_on:
    #   - kong-migration
    ports:
      - "8003:8000" # Proxy traffic
      - "8001:8001" # Admin API
      - "8002:8002" # Kong Manager
    volumes:
      - ./gateway.yaml:/usr/local/kong/declarative/gateway.yaml 

  
   