services:
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'

  # user microservice
  user:
      build: ../user
      ports:
      - '5001:5001'
      env_file:
      - ../user/.env
      depends_on:
      - rabbitmq
      restart: on-failure

  # weather microservice
  weather:
      build: ../weather
      ports:
      - '8081:8081'
      env_file:
      - ../weather/src/main/resources/.env
      restart: on-failure